on: [push, pull_request]
jobs:
  prejob:
    name: Skip Duplicate Actions

    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["README.md"]'
          do_not_skip: '["workflow_dispatch", "schedule"]'
  job:
    needs: prejob
    runs-on: ubuntu-latest
    if: needs.prejob.outputs.should_skip != 'true'
    steps:
      # This always fails after 60 seconds.
      - run: sleep 60 || false
